name: Bug Report
description: File a bug report
title: ":red_circle: "
labels: ["bug"]
assignees:
  - geriremenyi
body:
  - type: markdown
    id: intro
    attributes:
      value: |
        Please fill in the details to report a bug!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us, what did you expect to happen and what happened instead!
      placeholder: Tell us, what did you expect to happen and what happened instead!
    validations:
      required: true
  - type: dropdown
    id: version-selector
    attributes:
      label: What xyz version are you seeing the problem on?
      options:
        - 17.x
        - 16.x
        - 14.x
        - 12.x
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: extra-context
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true